name: FocalSV
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - cigar=0.1.3
  - cutesv=1.0.11
  - edlib=1.2.3
  - flye=2.9.1
  - hifiasm=0.14
  - shasta=0.10.0
  - libdeflate=1.0
  - longshot=0.4.5
  - minimap2=2.24
  - pysam=0.15.3
  - svim-asm=1.0.3
  - truvari=3.5.0
  - numpy=1.21.6
  - tqdm=4.61.2
  - scikit-allel=1.3.5
  - h5py=3.7.0
